//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBControlProyectoEntities : DbContext
    {
        public DBControlProyectoEntities()
            : base("name=DBControlProyectoEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblActividad> tblActividad { get; set; }
        public virtual DbSet<tblArea> tblArea { get; set; }
        public virtual DbSet<tblCargo> tblCargo { get; set; }
        public virtual DbSet<tblCuadernoObra> tblCuadernoObra { get; set; }
        public virtual DbSet<tblCuadernoProfesional> tblCuadernoProfesional { get; set; }
        public virtual DbSet<tblDocumento> tblDocumento { get; set; }
        public virtual DbSet<tblMenu> tblMenu { get; set; }
        public virtual DbSet<tblPermisos> tblPermisos { get; set; }
        public virtual DbSet<tblProfesional> tblProfesional { get; set; }
        public virtual DbSet<tblProfesional_Actividad> tblProfesional_Actividad { get; set; }
        public virtual DbSet<tblProfesional_Proyecto> tblProfesional_Proyecto { get; set; }
        public virtual DbSet<tblProfesional_Reunion> tblProfesional_Reunion { get; set; }
        public virtual DbSet<tblProyecto> tblProyecto { get; set; }
        public virtual DbSet<tblRecurso> tblRecurso { get; set; }
        public virtual DbSet<tblRecurso_Actividad> tblRecurso_Actividad { get; set; }
        public virtual DbSet<tblReporte> tblReporte { get; set; }
        public virtual DbSet<tblReporte_Actividad> tblReporte_Actividad { get; set; }
        public virtual DbSet<tblReunion> tblReunion { get; set; }
        public virtual DbSet<tblSubMenu> tblSubMenu { get; set; }
        public virtual DbSet<tblUsuario> tblUsuario { get; set; }
    
        public virtual ObjectResult<string> SP_A_ACTIVIDAD(string titulo, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, string description, Nullable<bool> estado, string creador, string proceso, Nullable<int> iDProyecto)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("fechaIni", fechaIni) :
                new ObjectParameter("fechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var creadorParameter = creador != null ?
                new ObjectParameter("creador", creador) :
                new ObjectParameter("creador", typeof(string));
    
            var procesoParameter = proceso != null ?
                new ObjectParameter("proceso", proceso) :
                new ObjectParameter("proceso", typeof(string));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_ACTIVIDAD", tituloParameter, fechaIniParameter, fechaFinParameter, descriptionParameter, estadoParameter, creadorParameter, procesoParameter, iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_AREA(Nullable<int> idNomAreaPadre, string nomArea, Nullable<int> iDProfesional, Nullable<int> iDProyecto)
        {
            var idNomAreaPadreParameter = idNomAreaPadre.HasValue ?
                new ObjectParameter("idNomAreaPadre", idNomAreaPadre) :
                new ObjectParameter("idNomAreaPadre", typeof(int));
    
            var nomAreaParameter = nomArea != null ?
                new ObjectParameter("nomArea", nomArea) :
                new ObjectParameter("nomArea", typeof(string));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_AREA", idNomAreaPadreParameter, nomAreaParameter, iDProfesionalParameter, iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_CARGO(string nomCargo, Nullable<bool> activo)
        {
            var nomCargoParameter = nomCargo != null ?
                new ObjectParameter("nomCargo", nomCargo) :
                new ObjectParameter("nomCargo", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_CARGO", nomCargoParameter, activoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_CuadernodeObra(string empresa, string contratista, Nullable<int> asientos, string tituloAsi, string tipAsi, Nullable<System.DateTime> fecha, string descripcion, string estado, Nullable<int> iDProyecto, Nullable<int> iDDocumento)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var contratistaParameter = contratista != null ?
                new ObjectParameter("contratista", contratista) :
                new ObjectParameter("contratista", typeof(string));
    
            var asientosParameter = asientos.HasValue ?
                new ObjectParameter("Asientos", asientos) :
                new ObjectParameter("Asientos", typeof(int));
    
            var tituloAsiParameter = tituloAsi != null ?
                new ObjectParameter("TituloAsi", tituloAsi) :
                new ObjectParameter("TituloAsi", typeof(string));
    
            var tipAsiParameter = tipAsi != null ?
                new ObjectParameter("TipAsi", tipAsi) :
                new ObjectParameter("TipAsi", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            var iDDocumentoParameter = iDDocumento.HasValue ?
                new ObjectParameter("IDDocumento", iDDocumento) :
                new ObjectParameter("IDDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_CuadernodeObra", empresaParameter, contratistaParameter, asientosParameter, tituloAsiParameter, tipAsiParameter, fechaParameter, descripcionParameter, estadoParameter, iDProyectoParameter, iDDocumentoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_CUADERNOPROFESIONAL(Nullable<int> idProfesional, Nullable<int> iDCuaderObra)
        {
            var idProfesionalParameter = idProfesional.HasValue ?
                new ObjectParameter("idProfesional", idProfesional) :
                new ObjectParameter("idProfesional", typeof(int));
    
            var iDCuaderObraParameter = iDCuaderObra.HasValue ?
                new ObjectParameter("IDCuaderObra", iDCuaderObra) :
                new ObjectParameter("IDCuaderObra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_CUADERNOPROFESIONAL", idProfesionalParameter, iDCuaderObraParameter);
        }
    
        public virtual ObjectResult<string> SP_A_DOCUMENTO(Nullable<int> iDDoc, string nombreDoc, string realNomb, byte[] dOC)
        {
            var iDDocParameter = iDDoc.HasValue ?
                new ObjectParameter("IDDoc", iDDoc) :
                new ObjectParameter("IDDoc", typeof(int));
    
            var nombreDocParameter = nombreDoc != null ?
                new ObjectParameter("NombreDoc", nombreDoc) :
                new ObjectParameter("NombreDoc", typeof(string));
    
            var realNombParameter = realNomb != null ?
                new ObjectParameter("RealNomb", realNomb) :
                new ObjectParameter("RealNomb", typeof(string));
    
            var dOCParameter = dOC != null ?
                new ObjectParameter("DOC", dOC) :
                new ObjectParameter("DOC", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_DOCUMENTO", iDDocParameter, nombreDocParameter, realNombParameter, dOCParameter);
        }
    
        public virtual ObjectResult<string> SP_A_MENU(string nombreMenu, string icono)
        {
            var nombreMenuParameter = nombreMenu != null ?
                new ObjectParameter("NombreMenu", nombreMenu) :
                new ObjectParameter("NombreMenu", typeof(string));
    
            var iconoParameter = icono != null ?
                new ObjectParameter("Icono", icono) :
                new ObjectParameter("Icono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_MENU", nombreMenuParameter, iconoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_PROFESIONAL(string dNI, Nullable<int> iDCargo, Nullable<int> iDProyectoActual, Nullable<int> iDReporte)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var iDCargoParameter = iDCargo.HasValue ?
                new ObjectParameter("IDCargo", iDCargo) :
                new ObjectParameter("IDCargo", typeof(int));
    
            var iDProyectoActualParameter = iDProyectoActual.HasValue ?
                new ObjectParameter("IDProyectoActual", iDProyectoActual) :
                new ObjectParameter("IDProyectoActual", typeof(int));
    
            var iDReporteParameter = iDReporte.HasValue ?
                new ObjectParameter("IDReporte", iDReporte) :
                new ObjectParameter("IDReporte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_PROFESIONAL", dNIParameter, iDCargoParameter, iDProyectoActualParameter, iDReporteParameter);
        }
    
        public virtual ObjectResult<string> SP_A_ProfesionalActividad(Nullable<int> iDProfesional, Nullable<int> iDActividad)
        {
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_ProfesionalActividad", iDProfesionalParameter, iDActividadParameter);
        }
    
        public virtual ObjectResult<string> SP_A_ProfesionalReunion(Nullable<int> iDProfesional_reunion, Nullable<int> iDProfesional, Nullable<int> iDReunion)
        {
            var iDProfesional_reunionParameter = iDProfesional_reunion.HasValue ?
                new ObjectParameter("IDProfesional_reunion", iDProfesional_reunion) :
                new ObjectParameter("IDProfesional_reunion", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var iDReunionParameter = iDReunion.HasValue ?
                new ObjectParameter("IDReunion", iDReunion) :
                new ObjectParameter("IDReunion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_ProfesionalReunion", iDProfesional_reunionParameter, iDProfesionalParameter, iDReunionParameter);
        }
    
        public virtual ObjectResult<string> SP_A_PROYECTO(string titulo, Nullable<System.DateTime> fechaIniPro, Nullable<System.DateTime> fechaFinPro, string descripcion, Nullable<bool> estado, string ubicacion, string distrito, string departamento, string imagen, string seguimiento, Nullable<int> iDProfesional)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaIniProParameter = fechaIniPro.HasValue ?
                new ObjectParameter("fechaIniPro", fechaIniPro) :
                new ObjectParameter("fechaIniPro", typeof(System.DateTime));
    
            var fechaFinProParameter = fechaFinPro.HasValue ?
                new ObjectParameter("fechaFinPro", fechaFinPro) :
                new ObjectParameter("fechaFinPro", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("Ubicacion", ubicacion) :
                new ObjectParameter("Ubicacion", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(string));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("departamento", departamento) :
                new ObjectParameter("departamento", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var seguimientoParameter = seguimiento != null ?
                new ObjectParameter("seguimiento", seguimiento) :
                new ObjectParameter("seguimiento", typeof(string));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_PROYECTO", tituloParameter, fechaIniProParameter, fechaFinProParameter, descripcionParameter, estadoParameter, ubicacionParameter, distritoParameter, departamentoParameter, imagenParameter, seguimientoParameter, iDProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_A_PROYECTOPROFESIONAL(Nullable<int> iDProyecto, Nullable<int> iDProfesional)
        {
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_PROYECTOPROFESIONAL", iDProyectoParameter, iDProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_A_RECURSO(string nombre, Nullable<int> cantidadStock, Nullable<decimal> costo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cantidadStockParameter = cantidadStock.HasValue ?
                new ObjectParameter("cantidadStock", cantidadStock) :
                new ObjectParameter("cantidadStock", typeof(int));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_RECURSO", nombreParameter, cantidadStockParameter, costoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_RECURSO_ACTIVIDAD(Nullable<int> iDRecurso, Nullable<int> iDActividad, Nullable<int> cantidad)
        {
            var iDRecursoParameter = iDRecurso.HasValue ?
                new ObjectParameter("IDRecurso", iDRecurso) :
                new ObjectParameter("IDRecurso", typeof(int));
    
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_RECURSO_ACTIVIDAD", iDRecursoParameter, iDActividadParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<string> SP_A_REPORTE(Nullable<System.DateTime> fechaRep, string descripcion, string estado, Nullable<int> iDDoc, Nullable<int> iDProfesional)
        {
            var fechaRepParameter = fechaRep.HasValue ?
                new ObjectParameter("FechaRep", fechaRep) :
                new ObjectParameter("FechaRep", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var iDDocParameter = iDDoc.HasValue ?
                new ObjectParameter("IDDoc", iDDoc) :
                new ObjectParameter("IDDoc", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_REPORTE", fechaRepParameter, descripcionParameter, estadoParameter, iDDocParameter, iDProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_A_REUNION(Nullable<int> iDReunion, string tipoDeReunion, Nullable<System.DateTime> fecha, string ubicacion, string tema, Nullable<bool> estado, Nullable<int> iDProyecto)
        {
            var iDReunionParameter = iDReunion.HasValue ?
                new ObjectParameter("IDReunion", iDReunion) :
                new ObjectParameter("IDReunion", typeof(int));
    
            var tipoDeReunionParameter = tipoDeReunion != null ?
                new ObjectParameter("tipoDeReunion", tipoDeReunion) :
                new ObjectParameter("tipoDeReunion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            var temaParameter = tema != null ?
                new ObjectParameter("tema", tema) :
                new ObjectParameter("tema", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_REUNION", iDReunionParameter, tipoDeReunionParameter, fechaParameter, ubicacionParameter, temaParameter, estadoParameter, iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_A_SUBMENU(Nullable<int> iDMenu, string nombreSubMenu, string controlador, string vista)
        {
            var iDMenuParameter = iDMenu.HasValue ?
                new ObjectParameter("IDMenu", iDMenu) :
                new ObjectParameter("IDMenu", typeof(int));
    
            var nombreSubMenuParameter = nombreSubMenu != null ?
                new ObjectParameter("NombreSubMenu", nombreSubMenu) :
                new ObjectParameter("NombreSubMenu", typeof(string));
    
            var controladorParameter = controlador != null ?
                new ObjectParameter("Controlador", controlador) :
                new ObjectParameter("Controlador", typeof(string));
    
            var vistaParameter = vista != null ?
                new ObjectParameter("Vista", vista) :
                new ObjectParameter("Vista", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_SUBMENU", iDMenuParameter, nombreSubMenuParameter, controladorParameter, vistaParameter);
        }
    
        public virtual ObjectResult<string> SP_A_USUARIO(string dNI, string nombre, string apellidos, string contraseña, string firma, string profesion, string correo, string telefono, string usrImagen)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var firmaParameter = firma != null ?
                new ObjectParameter("firma", firma) :
                new ObjectParameter("firma", typeof(string));
    
            var profesionParameter = profesion != null ?
                new ObjectParameter("profesion", profesion) :
                new ObjectParameter("profesion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var usrImagenParameter = usrImagen != null ?
                new ObjectParameter("usrImagen", usrImagen) :
                new ObjectParameter("usrImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_A_USUARIO", dNIParameter, nombreParameter, apellidosParameter, contraseñaParameter, firmaParameter, profesionParameter, correoParameter, telefonoParameter, usrImagenParameter);
        }
    
        public virtual ObjectResult<SP_C_ACTIVIDAD_Result> SP_C_ACTIVIDAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_ACTIVIDAD_Result>("SP_C_ACTIVIDAD");
        }
    
        public virtual ObjectResult<SP_C_AREA_Result> SP_C_AREA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_AREA_Result>("SP_C_AREA");
        }
    
        public virtual ObjectResult<SP_C_AREAPADRE_Result> SP_C_AREAPADRE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_AREAPADRE_Result>("SP_C_AREAPADRE");
        }
    
        public virtual ObjectResult<SP_C_CARGO_Result> SP_C_CARGO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_CARGO_Result>("SP_C_CARGO");
        }
    
        public virtual ObjectResult<SP_C_CUADERNAPROPROFESIONAL_Result> SP_C_CUADERNAPROPROFESIONAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_CUADERNAPROPROFESIONAL_Result>("SP_C_CUADERNAPROPROFESIONAL");
        }
    
        public virtual ObjectResult<SP_C_CuadernodeObra_Result> SP_C_CuadernodeObra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_CuadernodeObra_Result>("SP_C_CuadernodeObra");
        }
    
        public virtual ObjectResult<string> SP_C_DETALLEUSUARIO(Nullable<int> iDProfesional)
        {
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_C_DETALLEUSUARIO", iDProfesionalParameter);
        }
    
        public virtual ObjectResult<SP_C_DOCUMENTO_Result> SP_C_DOCUMENTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_DOCUMENTO_Result>("SP_C_DOCUMENTO");
        }
    
        public virtual ObjectResult<SP_C_MENU_Result> SP_C_MENU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_MENU_Result>("SP_C_MENU");
        }
    
        public virtual ObjectResult<SP_C_PERMISOS_Result> SP_C_PERMISOS(Nullable<int> iDCargo)
        {
            var iDCargoParameter = iDCargo.HasValue ?
                new ObjectParameter("IDCargo", iDCargo) :
                new ObjectParameter("IDCargo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PERMISOS_Result>("SP_C_PERMISOS", iDCargoParameter);
        }
    
        public virtual ObjectResult<SP_C_PERMISOSEDITAR_Result> SP_C_PERMISOSEDITAR(Nullable<int> iDCargo, string nombreSubMenu)
        {
            var iDCargoParameter = iDCargo.HasValue ?
                new ObjectParameter("IDCargo", iDCargo) :
                new ObjectParameter("IDCargo", typeof(int));
    
            var nombreSubMenuParameter = nombreSubMenu != null ?
                new ObjectParameter("NombreSubMenu", nombreSubMenu) :
                new ObjectParameter("NombreSubMenu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PERMISOSEDITAR_Result>("SP_C_PERMISOSEDITAR", iDCargoParameter, nombreSubMenuParameter);
        }
    
        public virtual ObjectResult<SP_C_PROFESIONAL_Result> SP_C_PROFESIONAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROFESIONAL_Result>("SP_C_PROFESIONAL");
        }
    
        public virtual ObjectResult<SP_C_ProfesionalActividad_Result> SP_C_ProfesionalActividad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_ProfesionalActividad_Result>("SP_C_ProfesionalActividad");
        }
    
        public virtual ObjectResult<SP_C_PROFESIONALID_Result> SP_C_PROFESIONALID(Nullable<int> iDProfesional)
        {
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROFESIONALID_Result>("SP_C_PROFESIONALID", iDProfesionalParameter);
        }
    
        public virtual ObjectResult<SP_C_PROFESIONALLOGIN_Result> SP_C_PROFESIONALLOGIN(string dNI, string contraseña)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROFESIONALLOGIN_Result>("SP_C_PROFESIONALLOGIN", dNIParameter, contraseñaParameter);
        }
    
        public virtual ObjectResult<SP_C_PROFESIONALRESPONSABLE_Result> SP_C_PROFESIONALRESPONSABLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROFESIONALRESPONSABLE_Result>("SP_C_PROFESIONALRESPONSABLE");
        }
    
        public virtual ObjectResult<SP_C_ProfesionalReunion_Result> SP_C_ProfesionalReunion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_ProfesionalReunion_Result>("SP_C_ProfesionalReunion");
        }
    
        public virtual ObjectResult<SP_C_PROYECTO_Result> SP_C_PROYECTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROYECTO_Result>("SP_C_PROYECTO");
        }
    
        public virtual ObjectResult<SP_C_PROYECTOLISTA_Result> SP_C_PROYECTOLISTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROYECTOLISTA_Result>("SP_C_PROYECTOLISTA");
        }
    
        public virtual ObjectResult<SP_C_PROYECTOPROFESIONAL_Result> SP_C_PROYECTOPROFESIONAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROYECTOPROFESIONAL_Result>("SP_C_PROYECTOPROFESIONAL");
        }
    
        public virtual ObjectResult<SP_C_PROYECTOPROFESIONALIMAGEN_Result> SP_C_PROYECTOPROFESIONALIMAGEN(Nullable<int> iDProfesional)
        {
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_PROYECTOPROFESIONALIMAGEN_Result>("SP_C_PROYECTOPROFESIONALIMAGEN", iDProfesionalParameter);
        }
    
        public virtual ObjectResult<SP_C_RECURSO_Result> SP_C_RECURSO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_RECURSO_Result>("SP_C_RECURSO");
        }
    
        public virtual ObjectResult<SP_C_RECURSO_ACTIVIDAD_Result> SP_C_RECURSO_ACTIVIDAD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_RECURSO_ACTIVIDAD_Result>("SP_C_RECURSO_ACTIVIDAD");
        }
    
        public virtual ObjectResult<SP_C_REPORTE_Result> SP_C_REPORTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_REPORTE_Result>("SP_C_REPORTE");
        }
    
        public virtual ObjectResult<SP_C_REUNION_Result> SP_C_REUNION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_REUNION_Result>("SP_C_REUNION");
        }
    
        public virtual ObjectResult<SP_C_USUARIO_Result> SP_C_USUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_USUARIO_Result>("SP_C_USUARIO");
        }
    
        public virtual ObjectResult<SP_C_USUARIODNI_Result> SP_C_USUARIODNI(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_C_USUARIODNI_Result>("SP_C_USUARIODNI", dNIParameter);
        }
    
        public virtual ObjectResult<string> SP_E_ACTIVIDAD(Nullable<int> iDActividad)
        {
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_ACTIVIDAD", iDActividadParameter);
        }
    
        public virtual ObjectResult<string> SP_E_AREA(Nullable<int> iDArea)
        {
            var iDAreaParameter = iDArea.HasValue ?
                new ObjectParameter("IDArea", iDArea) :
                new ObjectParameter("IDArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_AREA", iDAreaParameter);
        }
    
        public virtual ObjectResult<string> SP_E_CARGO(Nullable<int> iDCargo)
        {
            var iDCargoParameter = iDCargo.HasValue ?
                new ObjectParameter("IDCargo", iDCargo) :
                new ObjectParameter("IDCargo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_CARGO", iDCargoParameter);
        }
    
        public virtual ObjectResult<string> SP_E_CuadernodeObra(Nullable<int> iDCuaderObra)
        {
            var iDCuaderObraParameter = iDCuaderObra.HasValue ?
                new ObjectParameter("IDCuaderObra", iDCuaderObra) :
                new ObjectParameter("IDCuaderObra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_CuadernodeObra", iDCuaderObraParameter);
        }
    
        public virtual ObjectResult<string> SP_E_CUADERNOPROFESIONAL(Nullable<int> iDCuaderno_Profesional)
        {
            var iDCuaderno_ProfesionalParameter = iDCuaderno_Profesional.HasValue ?
                new ObjectParameter("IDCuaderno_Profesional", iDCuaderno_Profesional) :
                new ObjectParameter("IDCuaderno_Profesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_CUADERNOPROFESIONAL", iDCuaderno_ProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_E_DOCUMENTO(Nullable<int> iDDoc)
        {
            var iDDocParameter = iDDoc.HasValue ?
                new ObjectParameter("IDDoc", iDDoc) :
                new ObjectParameter("IDDoc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_DOCUMENTO", iDDocParameter);
        }
    
        public virtual ObjectResult<string> SP_E_PROFESIONAL(Nullable<int> idProfesional)
        {
            var idProfesionalParameter = idProfesional.HasValue ?
                new ObjectParameter("idProfesional", idProfesional) :
                new ObjectParameter("idProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_PROFESIONAL", idProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_E_ProfesionalActividad(Nullable<int> iDProfActividad)
        {
            var iDProfActividadParameter = iDProfActividad.HasValue ?
                new ObjectParameter("IDProfActividad", iDProfActividad) :
                new ObjectParameter("IDProfActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_ProfesionalActividad", iDProfActividadParameter);
        }
    
        public virtual ObjectResult<string> SP_E_ProfesionalReunion(Nullable<int> iDProfesional_reunion)
        {
            var iDProfesional_reunionParameter = iDProfesional_reunion.HasValue ?
                new ObjectParameter("IDProfesional_reunion", iDProfesional_reunion) :
                new ObjectParameter("IDProfesional_reunion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_ProfesionalReunion", iDProfesional_reunionParameter);
        }
    
        public virtual ObjectResult<string> SP_E_PROYECTO(Nullable<int> iDProyecto)
        {
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_PROYECTO", iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_E_PROYECTOPROFESIONAL(Nullable<int> iDProfeProyecto)
        {
            var iDProfeProyectoParameter = iDProfeProyecto.HasValue ?
                new ObjectParameter("IDProfeProyecto", iDProfeProyecto) :
                new ObjectParameter("IDProfeProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_PROYECTOPROFESIONAL", iDProfeProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_E_RECURSO(Nullable<int> iDRecurso)
        {
            var iDRecursoParameter = iDRecurso.HasValue ?
                new ObjectParameter("IDRecurso", iDRecurso) :
                new ObjectParameter("IDRecurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_RECURSO", iDRecursoParameter);
        }
    
        public virtual ObjectResult<string> SP_E_RECURSO_ACTIVIDAD(Nullable<int> idRecursoActividad)
        {
            var idRecursoActividadParameter = idRecursoActividad.HasValue ?
                new ObjectParameter("idRecursoActividad", idRecursoActividad) :
                new ObjectParameter("idRecursoActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_RECURSO_ACTIVIDAD", idRecursoActividadParameter);
        }
    
        public virtual ObjectResult<string> SP_E_Reporte(Nullable<int> iDReport)
        {
            var iDReportParameter = iDReport.HasValue ?
                new ObjectParameter("IDReport", iDReport) :
                new ObjectParameter("IDReport", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_Reporte", iDReportParameter);
        }
    
        public virtual ObjectResult<string> SP_E_REUNION(Nullable<int> iDReunion)
        {
            var iDReunionParameter = iDReunion.HasValue ?
                new ObjectParameter("IDReunion", iDReunion) :
                new ObjectParameter("IDReunion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_REUNION", iDReunionParameter);
        }
    
        public virtual ObjectResult<string> SP_E_USUARIO(string dNI)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_E_USUARIO", dNIParameter);
        }
    
        public virtual ObjectResult<string> SP_M_ACTIVIDAD(Nullable<int> iDActividad, string titulo, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, string description, Nullable<bool> estado, string creador, string proceso, Nullable<int> iDProyecto)
        {
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("fechaIni", fechaIni) :
                new ObjectParameter("fechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var creadorParameter = creador != null ?
                new ObjectParameter("creador", creador) :
                new ObjectParameter("creador", typeof(string));
    
            var procesoParameter = proceso != null ?
                new ObjectParameter("proceso", proceso) :
                new ObjectParameter("proceso", typeof(string));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_ACTIVIDAD", iDActividadParameter, tituloParameter, fechaIniParameter, fechaFinParameter, descriptionParameter, estadoParameter, creadorParameter, procesoParameter, iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_M_ACTIVIDADPROCESO(Nullable<int> iDActividad, string proceso)
        {
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            var procesoParameter = proceso != null ?
                new ObjectParameter("proceso", proceso) :
                new ObjectParameter("proceso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_ACTIVIDADPROCESO", iDActividadParameter, procesoParameter);
        }
    
        public virtual ObjectResult<SP_M_ActualizarPermisos_Result> SP_M_ActualizarPermisos(string detalle)
        {
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_M_ActualizarPermisos_Result>("SP_M_ActualizarPermisos", detalleParameter);
        }
    
        public virtual ObjectResult<string> SP_M_AREA(Nullable<int> iDArea, Nullable<int> idNombreArea, string nomArea, Nullable<int> iDProfesional, Nullable<int> iDProyecto)
        {
            var iDAreaParameter = iDArea.HasValue ?
                new ObjectParameter("IDArea", iDArea) :
                new ObjectParameter("IDArea", typeof(int));
    
            var idNombreAreaParameter = idNombreArea.HasValue ?
                new ObjectParameter("idNombreArea", idNombreArea) :
                new ObjectParameter("idNombreArea", typeof(int));
    
            var nomAreaParameter = nomArea != null ?
                new ObjectParameter("nomArea", nomArea) :
                new ObjectParameter("nomArea", typeof(string));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_AREA", iDAreaParameter, idNombreAreaParameter, nomAreaParameter, iDProfesionalParameter, iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_M_CARGO(Nullable<int> iDCargo, string nomCargo, Nullable<bool> activo)
        {
            var iDCargoParameter = iDCargo.HasValue ?
                new ObjectParameter("IDCargo", iDCargo) :
                new ObjectParameter("IDCargo", typeof(int));
    
            var nomCargoParameter = nomCargo != null ?
                new ObjectParameter("nomCargo", nomCargo) :
                new ObjectParameter("nomCargo", typeof(string));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_CARGO", iDCargoParameter, nomCargoParameter, activoParameter);
        }
    
        public virtual ObjectResult<string> SP_M_CuadernodeObra(Nullable<int> iDCuaderObra, string empresa, string contratista, Nullable<int> asientos, string tituloAsi, string tipAsi, Nullable<System.DateTime> fecha, string descripcion, string estado, Nullable<int> iDProyecto, Nullable<int> iDDocumento)
        {
            var iDCuaderObraParameter = iDCuaderObra.HasValue ?
                new ObjectParameter("IDCuaderObra", iDCuaderObra) :
                new ObjectParameter("IDCuaderObra", typeof(int));
    
            var empresaParameter = empresa != null ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(string));
    
            var contratistaParameter = contratista != null ?
                new ObjectParameter("contratista", contratista) :
                new ObjectParameter("contratista", typeof(string));
    
            var asientosParameter = asientos.HasValue ?
                new ObjectParameter("Asientos", asientos) :
                new ObjectParameter("Asientos", typeof(int));
    
            var tituloAsiParameter = tituloAsi != null ?
                new ObjectParameter("TituloAsi", tituloAsi) :
                new ObjectParameter("TituloAsi", typeof(string));
    
            var tipAsiParameter = tipAsi != null ?
                new ObjectParameter("TipAsi", tipAsi) :
                new ObjectParameter("TipAsi", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            var iDDocumentoParameter = iDDocumento.HasValue ?
                new ObjectParameter("IDDocumento", iDDocumento) :
                new ObjectParameter("IDDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_CuadernodeObra", iDCuaderObraParameter, empresaParameter, contratistaParameter, asientosParameter, tituloAsiParameter, tipAsiParameter, fechaParameter, descripcionParameter, estadoParameter, iDProyectoParameter, iDDocumentoParameter);
        }
    
        public virtual ObjectResult<string> SP_M_CuadernoProfesional(Nullable<int> iDCuaderno_Profesional, Nullable<int> idProfesional, Nullable<int> iDCuaderObra)
        {
            var iDCuaderno_ProfesionalParameter = iDCuaderno_Profesional.HasValue ?
                new ObjectParameter("IDCuaderno_Profesional", iDCuaderno_Profesional) :
                new ObjectParameter("IDCuaderno_Profesional", typeof(int));
    
            var idProfesionalParameter = idProfesional.HasValue ?
                new ObjectParameter("idProfesional", idProfesional) :
                new ObjectParameter("idProfesional", typeof(int));
    
            var iDCuaderObraParameter = iDCuaderObra.HasValue ?
                new ObjectParameter("IDCuaderObra", iDCuaderObra) :
                new ObjectParameter("IDCuaderObra", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_CuadernoProfesional", iDCuaderno_ProfesionalParameter, idProfesionalParameter, iDCuaderObraParameter);
        }
    
        public virtual ObjectResult<string> SP_M_DOCUMENTO(Nullable<int> iDDoc, string nombreDoc, string realNomb, byte[] dOC)
        {
            var iDDocParameter = iDDoc.HasValue ?
                new ObjectParameter("IDDoc", iDDoc) :
                new ObjectParameter("IDDoc", typeof(int));
    
            var nombreDocParameter = nombreDoc != null ?
                new ObjectParameter("NombreDoc", nombreDoc) :
                new ObjectParameter("NombreDoc", typeof(string));
    
            var realNombParameter = realNomb != null ?
                new ObjectParameter("RealNomb", realNomb) :
                new ObjectParameter("RealNomb", typeof(string));
    
            var dOCParameter = dOC != null ?
                new ObjectParameter("DOC", dOC) :
                new ObjectParameter("DOC", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_DOCUMENTO", iDDocParameter, nombreDocParameter, realNombParameter, dOCParameter);
        }
    
        public virtual int SP_M_Permisos(Nullable<int> iDPermisos, Nullable<bool> activo, Nullable<bool> edicion)
        {
            var iDPermisosParameter = iDPermisos.HasValue ?
                new ObjectParameter("IDPermisos", iDPermisos) :
                new ObjectParameter("IDPermisos", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var edicionParameter = edicion.HasValue ?
                new ObjectParameter("Edicion", edicion) :
                new ObjectParameter("Edicion", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_M_Permisos", iDPermisosParameter, activoParameter, edicionParameter);
        }
    
        public virtual ObjectResult<string> SP_M_PROFESIONAL(Nullable<int> iDProfesional, string dNI, Nullable<int> iDCargo, Nullable<int> iDReporte, Nullable<int> iDProyectoActual)
        {
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var iDCargoParameter = iDCargo.HasValue ?
                new ObjectParameter("IDCargo", iDCargo) :
                new ObjectParameter("IDCargo", typeof(int));
    
            var iDReporteParameter = iDReporte.HasValue ?
                new ObjectParameter("IDReporte", iDReporte) :
                new ObjectParameter("IDReporte", typeof(int));
    
            var iDProyectoActualParameter = iDProyectoActual.HasValue ?
                new ObjectParameter("IDProyectoActual", iDProyectoActual) :
                new ObjectParameter("IDProyectoActual", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_PROFESIONAL", iDProfesionalParameter, dNIParameter, iDCargoParameter, iDReporteParameter, iDProyectoActualParameter);
        }
    
        public virtual ObjectResult<string> SP_M_ProfesionalActividad(Nullable<int> iDProfActividad, Nullable<int> iDProfesional, Nullable<int> iDActividad)
        {
            var iDProfActividadParameter = iDProfActividad.HasValue ?
                new ObjectParameter("IDProfActividad", iDProfActividad) :
                new ObjectParameter("IDProfActividad", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_ProfesionalActividad", iDProfActividadParameter, iDProfesionalParameter, iDActividadParameter);
        }
    
        public virtual ObjectResult<string> SP_M_ProfesionalReunion(Nullable<int> iDProfesional_reunion, Nullable<int> iDProfesional, Nullable<int> iDReunion)
        {
            var iDProfesional_reunionParameter = iDProfesional_reunion.HasValue ?
                new ObjectParameter("IDProfesional_reunion", iDProfesional_reunion) :
                new ObjectParameter("IDProfesional_reunion", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            var iDReunionParameter = iDReunion.HasValue ?
                new ObjectParameter("IDReunion", iDReunion) :
                new ObjectParameter("IDReunion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_ProfesionalReunion", iDProfesional_reunionParameter, iDProfesionalParameter, iDReunionParameter);
        }
    
        public virtual ObjectResult<string> SP_M_PROYECTO(Nullable<int> iDProyecto, string titulo, Nullable<System.DateTime> fechaIniPro, Nullable<System.DateTime> fechaFinPro, string descripcion, Nullable<bool> estado, string ubicacion, string distrito, string departamento, string imagen, string seguimiento, Nullable<int> iDProfesional)
        {
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaIniProParameter = fechaIniPro.HasValue ?
                new ObjectParameter("fechaIniPro", fechaIniPro) :
                new ObjectParameter("fechaIniPro", typeof(System.DateTime));
    
            var fechaFinProParameter = fechaFinPro.HasValue ?
                new ObjectParameter("fechaFinPro", fechaFinPro) :
                new ObjectParameter("fechaFinPro", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("Ubicacion", ubicacion) :
                new ObjectParameter("Ubicacion", typeof(string));
    
            var distritoParameter = distrito != null ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(string));
    
            var departamentoParameter = departamento != null ?
                new ObjectParameter("departamento", departamento) :
                new ObjectParameter("departamento", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            var seguimientoParameter = seguimiento != null ?
                new ObjectParameter("seguimiento", seguimiento) :
                new ObjectParameter("seguimiento", typeof(string));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_PROYECTO", iDProyectoParameter, tituloParameter, fechaIniProParameter, fechaFinProParameter, descripcionParameter, estadoParameter, ubicacionParameter, distritoParameter, departamentoParameter, imagenParameter, seguimientoParameter, iDProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_M_PROYECTOPROFESIONAL(Nullable<int> iDProfeProyecto, Nullable<int> iDProyecto, Nullable<int> iDProfesional)
        {
            var iDProfeProyectoParameter = iDProfeProyecto.HasValue ?
                new ObjectParameter("IDProfeProyecto", iDProfeProyecto) :
                new ObjectParameter("IDProfeProyecto", typeof(int));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_PROYECTOPROFESIONAL", iDProfeProyectoParameter, iDProyectoParameter, iDProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_M_RECURSO(Nullable<int> iDRecurso, string nombre, Nullable<int> cantidadStock, Nullable<decimal> costo)
        {
            var iDRecursoParameter = iDRecurso.HasValue ?
                new ObjectParameter("IDRecurso", iDRecurso) :
                new ObjectParameter("IDRecurso", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var cantidadStockParameter = cantidadStock.HasValue ?
                new ObjectParameter("cantidadStock", cantidadStock) :
                new ObjectParameter("cantidadStock", typeof(int));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_RECURSO", iDRecursoParameter, nombreParameter, cantidadStockParameter, costoParameter);
        }
    
        public virtual ObjectResult<string> SP_M_RECURSO_ACTIVIDAD(Nullable<int> idRecursoActividad, Nullable<int> iDRecurso, Nullable<int> iDActividad, Nullable<int> cantidad)
        {
            var idRecursoActividadParameter = idRecursoActividad.HasValue ?
                new ObjectParameter("idRecursoActividad", idRecursoActividad) :
                new ObjectParameter("idRecursoActividad", typeof(int));
    
            var iDRecursoParameter = iDRecurso.HasValue ?
                new ObjectParameter("IDRecurso", iDRecurso) :
                new ObjectParameter("IDRecurso", typeof(int));
    
            var iDActividadParameter = iDActividad.HasValue ?
                new ObjectParameter("IDActividad", iDActividad) :
                new ObjectParameter("IDActividad", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_RECURSO_ACTIVIDAD", idRecursoActividadParameter, iDRecursoParameter, iDActividadParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<string> SP_M_REPORTE(Nullable<int> iDReport, Nullable<System.DateTime> fechaRep, string descripcion, string estado, Nullable<int> iDDoc, Nullable<int> iDProfesional)
        {
            var iDReportParameter = iDReport.HasValue ?
                new ObjectParameter("IDReport", iDReport) :
                new ObjectParameter("IDReport", typeof(int));
    
            var fechaRepParameter = fechaRep.HasValue ?
                new ObjectParameter("FechaRep", fechaRep) :
                new ObjectParameter("FechaRep", typeof(System.DateTime));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var iDDocParameter = iDDoc.HasValue ?
                new ObjectParameter("IDDoc", iDDoc) :
                new ObjectParameter("IDDoc", typeof(int));
    
            var iDProfesionalParameter = iDProfesional.HasValue ?
                new ObjectParameter("IDProfesional", iDProfesional) :
                new ObjectParameter("IDProfesional", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_REPORTE", iDReportParameter, fechaRepParameter, descripcionParameter, estadoParameter, iDDocParameter, iDProfesionalParameter);
        }
    
        public virtual ObjectResult<string> SP_M_REUNION(Nullable<int> iDReunion, string tipoDeReunion, Nullable<System.DateTime> fecha, string ubicacion, string tema, Nullable<bool> estado, Nullable<int> iDProyecto)
        {
            var iDReunionParameter = iDReunion.HasValue ?
                new ObjectParameter("IDReunion", iDReunion) :
                new ObjectParameter("IDReunion", typeof(int));
    
            var tipoDeReunionParameter = tipoDeReunion != null ?
                new ObjectParameter("tipoDeReunion", tipoDeReunion) :
                new ObjectParameter("tipoDeReunion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var ubicacionParameter = ubicacion != null ?
                new ObjectParameter("ubicacion", ubicacion) :
                new ObjectParameter("ubicacion", typeof(string));
    
            var temaParameter = tema != null ?
                new ObjectParameter("tema", tema) :
                new ObjectParameter("tema", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            var iDProyectoParameter = iDProyecto.HasValue ?
                new ObjectParameter("IDProyecto", iDProyecto) :
                new ObjectParameter("IDProyecto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_REUNION", iDReunionParameter, tipoDeReunionParameter, fechaParameter, ubicacionParameter, temaParameter, estadoParameter, iDProyectoParameter);
        }
    
        public virtual ObjectResult<string> SP_M_USUARIO(string dNI, string nombre, string apellidos, string contraseña, string firma, string profesion, string correo, string telefono, string usrImagen)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var firmaParameter = firma != null ?
                new ObjectParameter("firma", firma) :
                new ObjectParameter("firma", typeof(string));
    
            var profesionParameter = profesion != null ?
                new ObjectParameter("profesion", profesion) :
                new ObjectParameter("profesion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var usrImagenParameter = usrImagen != null ?
                new ObjectParameter("usrImagen", usrImagen) :
                new ObjectParameter("usrImagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_M_USUARIO", dNIParameter, nombreParameter, apellidosParameter, contraseñaParameter, firmaParameter, profesionParameter, correoParameter, telefonoParameter, usrImagenParameter);
        }
    }
}
