//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArea()
        {
            this.tblArea1 = new HashSet<tblArea>();
        }
    
        public int IDArea { get; set; }
        public Nullable<int> IdNomAreaPadre { get; set; }
        public string nomArea { get; set; }
        public int IDProfesional { get; set; }
        public Nullable<int> IDProyecto { get; set; }
    
        public virtual tblProfesional tblProfesional { get; set; }
        public virtual tblProyecto tblProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArea> tblArea1 { get; set; }
        public virtual tblArea tblArea2 { get; set; }
    }
}
