//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblActividad()
        {
            this.tblProfesional_Actividad = new HashSet<tblProfesional_Actividad>();
            this.tblRecurso_Actividad = new HashSet<tblRecurso_Actividad>();
        }
    
        public int IDActividad { get; set; }
        public string titActividad { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public string Descripcion { get; set; }
        public bool estado { get; set; }
        public string creador { get; set; }
        public string proceso { get; set; }
        public int IDProyecto { get; set; }
    
        public virtual tblProyecto tblProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfesional_Actividad> tblProfesional_Actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecurso_Actividad> tblRecurso_Actividad { get; set; }
    }
}
