//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCuadernoObra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCuadernoObra()
        {
            this.tblCuadernoProfesional = new HashSet<tblCuadernoProfesional>();
        }
    
        public int IDCuaderObra { get; set; }
        public string empresa { get; set; }
        public string contratista { get; set; }
        public int Asientos { get; set; }
        public string TituloAsi { get; set; }
        public string TipAsi { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public int IDProyecto { get; set; }
        public int IDDocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCuadernoProfesional> tblCuadernoProfesional { get; set; }
        public virtual tblDocumento tblDocumento { get; set; }
        public virtual tblProyecto tblProyecto { get; set; }
    }
}
