//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfesional_Reunion
    {
        public int IDProfesional_reunion { get; set; }
        public int IDProfesional { get; set; }
        public int IDReunion { get; set; }
    
        public virtual tblProfesional tblProfesional { get; set; }
        public virtual tblReunion tblReunion { get; set; }
    }
}
