//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReunion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReunion()
        {
            this.tblActas = new HashSet<tblActas>();
            this.tblProfesional_Reunion = new HashSet<tblProfesional_Reunion>();
        }
    
        public int IDReunion { get; set; }
        public string tipoDeReunion { get; set; }
        public System.DateTime fecha { get; set; }
        public string ubicacion { get; set; }
        public string tema { get; set; }
        public bool estado { get; set; }
        public int IDProyecto { get; set; }
        public int IDProfesional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblActas> tblActas { get; set; }
        public virtual tblProfesional tblProfesional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfesional_Reunion> tblProfesional_Reunion { get; set; }
        public virtual tblProyecto tblProyecto { get; set; }
    }
}
