//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReporte()
        {
            this.tblProfesional = new HashSet<tblProfesional>();
        }
    
        public int IDReport { get; set; }
        public System.DateTime FechaRep { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public int IDDoc { get; set; }
        public int IDProfesional { get; set; }
    
        public virtual tblDocumento tblDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProfesional> tblProfesional { get; set; }
        public virtual tblProfesional tblProfesional1 { get; set; }
    }
}
