//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaControlProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSubMenu()
        {
            this.tblPermisos = new HashSet<tblPermisos>();
        }
    
        public int IDSubMenu { get; set; }
        public int IDMenu { get; set; }
        public string NombreSubMenu { get; set; }
        public string Controlador { get; set; }
        public string Vista { get; set; }
        public bool Activo { get; set; }
        public bool Edicion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual tblMenu tblMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermisos> tblPermisos { get; set; }
    }
}
